# @package _global_
input_data_path: 'data/raw/train.csv'
output_model_path: 'models/model.pkl'
metric_path: 'models/metrics.json'
defaults:
  - splitting_params: val_20_rand_14
  - feature_params: features
  - train_params: random_forest